* ASAP

** DONE Parse errors don't produce proper error messages.

  When I tried to run the executable on a file I actually wanted to
  use, I got a parse error. That was correct, but info on where the
  error was would obviously be useful. We need at least the line number....

** DONE When transactions don't balance, should report ALL of the problematic transactions.

** Should be possible to get running balance even if assertions don't succeed.
   Otherwise, how to debug the assertions?
   Probably add an ignore-assertions flag.

** If we get error opening excel output file:
*** DONE Don't crash - catch it
    -  no such directory
    - can't write to that file
*** DONE get that error after reading/validating the input

* Bugs
** DONE Accounts reported with "canonical", not "input" names

   When we process a set of transactions, top-level Accounts structure get
   created with wrong ".input" field - they get the account's canonical name,
   not it's "input" name.

   Hmmm ... This is problem in balances-by-date report, but not in balances report....

* Enhancements
** Validation
*** input/transaction files
**** DONE Need to make sure transactions at least balance!
**** DONE Need to ensure account names are valid
     Do this before checking transactions balance - we need valid
     names to actually calculate the balance.
**** DONE Need to make balance-verify statements work!
**** Convert whitespace in descriptions to space characters
*** Command-line arguments
**** date arguments need to be checked for validity
**** date arguments need to be sorted into ascending order
**** account arguments need to be checked for validity

** Better exception handling
   At the moment, we don't even handle missing input file exceptions.
** Reporting
*** balances-by-date
    Maybe put in a starting-balance to remove need to display
    transactions before the first mentioned date? Could make it easier
    to read once we have several years worth of data....
*** Add from/to dates to register report
    If given a <start-date>, it should add all transactions from
    beginning, and then:
    - begin with an opening-balance at <start-date>
    If given an <end-date>, it should not print transactions after
    that date.
*** Excel-formatted output
**** Add transactions: txnid/description/amount to balance report (excel version only)
*** text-formatted
**** Justify columns
     appropriately when producing (default) text-formatted reports.

** Multi-currency
** Multiple entities
   Handle multiple entities in a single transaction file.
** Also - all the XXX & TODO comments throughout the code.
** Non-empty list type
   Where we raise exceptions for empty lists - we could structure the
   list type so its non-empty - in particular with
   accountNameComponents. A generic non-empty list type type might
   avoid a bit of exception raising code that theoretically can't be
   thrown anyway.
